name: prelimproject_plaza
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.2
  sdk: ">=2.19.0 <3.0.0"

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  riverpod: ^2.0.3

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  lints: ^2.0.0
